### ISSUE TITLE
Error in post build on windows

### ISSUE THREAD

**Issue by jayscope** [AirConsole/airconsole-unity-plugin#14]
Issue seems to be caused by the path being split by the system's path separator, but the actual path being split is not necessarily composed of that specific system's separators.

`FileNotFoundException: D:/Projects/loony-lancers/Unity/Builds/Build/D:/Projects/loony-lancers/Unity/Builds.json does not exist
System.IO.File.Move (System.String sourceFileName, System.String destFileName) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/File.cs:318)
NDream.AirConsole.Editor.PostBuildProcess.OnPostprocessBuild (BuildTarget target, System.String pathToBuiltProject) (at Assets/AirConsole/scripts/editor/PostBuildProcess.cs:32)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.Build.BuildPipelineInterfaces+AttributeCallbackWrapper.OnPostprocessBuild (BuildTarget target, System.String path) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:65)
UnityEditor.Build.BuildPipelineInterfaces.OnBuildPostProcess (BuildTarget platform, System.String path, Boolean strict) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:274)
UnityEditor.HostView:OnGUI()`

**Comment by Frozenfire92** [comment]
#15  is a good temporary fix for anyone experiencing this issue. I believe #16 is also duplicating this. I think [this reddit thread](https://www.reddit.com/r/airconsole/comments/6c80hu/dev_question_unity_561_webgl_build_cannot_find/) is also the same issue. So that leads me to believe this bug started somewhere in 5.6 cycle and is still around for 2017.1

I think the root of this bug may lie on Unity's end, as the [documentation](https://docs.unity3d.com/Manual/webgl-building.html) states that the following file will be created when being built:

> A MyProject.json JSON file containing all the necessary information about your build. The URL of this JSON file is provided as an argument for the Unity Loader when the build is instantiated. JSON file contains URLs of all the other build files, which can be absolute or relative to the location of the JSON file. JSON may contain additional Module parameters, such as the splash screen style or the initial size of the memory heap.

However it seems that `MyProject` is actually the name of the directory you build to instead. Unsure if this is desired and the documentation is wrong, or if this is wrong and the documentation is right. Either way this should be brought to Unity's attention.

Looking at a build I created (in `Builds_WEBGL`) I see

```
Builds_WEBGL/
├── airconsole-unity-plugin.js
├── Build
│   ├── Builds_WEBGL.asm.code.unityweb
│   ├── Builds_WEBGL.asm.framework.unityweb
│   ├── Builds_WEBGL.asm.library.unityweb
│   ├── Builds_WEBGL.asm.memory.unityweb
│   ├── Builds_WEBGL.data.unityweb
│   ├── Builds_WEBGL.json
│   └── UnityLoader.js
├── controller.html
├── screen.html
└── TemplateData
    ├── CSSPlugin.js
    ├── favicon.ico
    ├── fullbar.png
    ├── gifLoader.gif
    ├── loadingbar.png
    ├── loading-screen.png
    ├── progresslogo.png
    ├── style.css
    ├── tweenjs-0.6.0.min.js
    └── UnityProgress.js
```

Proving the issue.  #15 works because it replaces `pathDirectories [pathDirectories.Length - 1]` which gives you `C:/Users/you/Dev/Game/Builds_WEBGL` with `Path.GetFileName(pathToBuiltProject)` which gives you `Builds_WEBGL` which does have a corresponding json file in the Builds directory.
